# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create and build image and deploy using helm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  repo: lwplapbs
  imge: nodejsapp

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest


    steps:

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: echo step variables
        run: echo "${{ github.run_id }}"
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: lwplapbs/nodejsapp:${{ github.run_id }}

      - name: update kubeconfig
        run: |
          aws eks --region us-east-2 update-kubeconfig --name eks-cluster
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: 'us-east-2'

      - name: 'Deploy'
        uses: 'deliverybot/helm@v1'
        with:
          release: 'digital-nodeapp'
          namespace: 'default'
          repo: 'https://thedevopsstore.github.io/lwplabs-charts/'
          chart: lwplabs-charts
          values: |
            image.tag: ${{ github.run_id }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: 'us-east-2'
